# Generated by Django 2.0.8 on 2019-06-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_name', models.CharField(max_length=100)),
                ('Name_student', models.CharField(max_length=100)),
                ('USN', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
            ],
        ),
    ]
